### ISSUE TITLE
OCI Initial Delivery

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/python-gardenlinux-cli#17]
# Epic: OCI Initial Delivery

## Scope

As Garden Linux adopter, I want to be able to pull my image of choice via Open Container Initiative (OCI)[1] Image Specification (image-spec) container layers, served for me from public registry. 

[1] See https://opencontainers.org/about/overview/

## High Level Architecture

![349417181-b56c816c-c4cd-47bd-923c-e5a7215839a1](https://github.com/user-attachments/assets/17fe6601-fe1b-4c46-ba37-a2e08214ab7b)

The Architecture Diagram above shows the existing Garden Linux pipeline state, and the OCI extensions for the pipelines. 
Architectural decisions are:
- OCI pipelines are not blocking
- OCI Images are incrementally extended. (build artifacts, test artifacts, audit artifacts, arbitrary artifacts) 
- OCI tool is a CLI that can be invoked from local workstation or from pipeline, and is independent of CI/CD syntax

## Architectural alignments and discussions

Before the initial implementation, a [request for discussion](https://github.com/gardenlinux/RFD/blob/0012/docs/rfd-12.md) was prepared. Summary of discussion is included in the RFD linked above.  

## Definition of done
- [ ] Tool to package Garden Linux release artefacts into OCI images, and upload them to a target OCI registry
    - https://github.com/gardenlinux/gl-oci
- [ ] Integration of tooling into release build pipelines of Garden Linux, so that Garden Linux release artefacts can be incrementally be attached to an OCI-image until it reaches a defined state of "final" including cryptographic signatures

### Nov

**Bugs**

- 

**Enhancements**
- https://github.com/gardenlinux/python-gardenlinux-cli/issues/22
- https://github.com/gardenlinux/python-gardenlinux-cli/issues/19

### Oct

**Bugs**

**Enhancements**

### September 
**Bugs**

**Enhancements**
- https://github.com/gardenlinux/python-gardenlinux-cli/issues/22
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/38
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/42
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/43
- https://github.com/gardenlinux/python-gardenlinux-cli/issues/18
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/44
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/46
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/47
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/48
- https://github.com/gardenlinux/python-gardenlinux-cli/issues/21
- https://github.com/gardenlinux/gardenlinux/issues/2441
- https://github.com/gardenlinux/python-gardenlinux-cli/issues/3

### August
**Bugs**
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/23
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/22
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/21
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/20

**Enhancements**
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/29
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/28
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/27
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/16
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/26
- https://github.com/gardenlinux/gardenlinux/issues/2441
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/25
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/24
- https://github.com/gardenlinux/python-gardenlinux-cli/issues/23
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/19
- https://github.com/gardenlinux/parse_features_lib/issues/1
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/18
- https://github.com/gardenlinux/parse_features_lib/issues/4
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/17
- https://github.com/gardenlinux/parse_features_lib/issues/10
- https://github.com/gardenlinux/python-gardenlinux-lib/issues/30

### July
- Topic has been handled with lower priority due to on-site workshop, urgent release work, sick leave.

### June
- https://github.com/gardenlinux/process/issues/53
- ✅  Design and document how to integrate OCM with OCI 
- ✅  Setup Development Environment (poetry, zot, makefile)
- ✅  Create OCI Image manifest and push it to a registry 
- ✅  Extend an existing OCI Image manifest with additional layer

**Comment by mxmxchere** [comment]
The OCI pushing is now merged to nightly (since last week).
