### ISSUE TITLE
[OCI] Feature to upload container images

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/python-gardenlinux-cli#22]
### What would you like to be added
Container images must also be uploaded to the OCI Index via the OCI delivery gear. 

Migrating to single package name is a separate task that we first need to verify if this is required. 

Container images that will be placed to the OCI Index eventually:
- package build container
- kernel driver build container
- base container for users (current gardenlinux container)
- test container 

### Why is this needed
- Sign referenced container digests 
- Single place to check for completeness 
- Signature verification of all components before creating open component model for Garden Linux release.
    - containers are part of the release, they are re-build for each release
        - kernel driver build container requires the correct kernel headers used for the respective image (mapped via version)
        - package build container requires the correct apt sources configured for the respective image (mapped via version)
        - base container has the same apt packages (mapped via version)

### Notes
We do not migrate the OCI delivery target to the package name [gardenlinux](https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux) just yet, and we will keep the current way of publishing container images in place until we want to migrate.

**Comment by mxmxchere** [comment]
So I would say we can first stick with podman's logic for pushing container artifacts. The two tools podman & python-gardenlinux-cli work together in this workflow here:
https://github.com/gardenlinux/gardenlinux/blob/integrate-oci-delivery-in-pipelines3/.github/workflows/upload_oci.yml
