### ISSUE TITLE
Separate log messages from stdout

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/python-gardenlinux-cli#23]
**What would you like to be added**:

* Add more log messages (different log levels)
* Do not print log messages to stdout, stdout should be usable for bash pipes
* set exit codes

**Why is this needed**:
* this improves usability and presentability of this tool 
* required for gardenlinux/gardenlinux#2441, so that stdout is clean

**Comment by mxmxchere** [comment]
We changed the log output a bit while refactoring. Now it is less verbose but still pushed artifacts and their digests are logged.
